server:
  servlet:
    context-path: /smaster-home
spring:
  profiles:
    activate: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/smaster
    username: smaster
    password: smaster
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

