server:
  servlet:
    context-path: /smaster-home
spring:
  profiles:
    activate: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/smaster
    username: smaster
    password: smaster
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true
jwt:
  secret : smaster   